# Generated by Django 3.1.1 on 2020-12-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20171107_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(default='Kenya', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('mailing', 'Mailing address'), ('shipping', 'Shipping address')], max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=120),
        ),
    ]
