# Generated by Django 3.1.1 on 2021-02-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_timestamp'),
        ('products', '0010_product_is_digital'),
    ]

    operations = [
    ]
