# Generated by Django 3.1.1 on 2021-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
