# Generated by Django 3.1.1 on 2021-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20171018_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
