# Generated by Django 3.1.1 on 2021-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210203_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
