# Generated by Django 3.1.1 on 2021-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210206_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CustomerID',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stockcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
