# Generated by Django 3.1.1 on 2021-02-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stockcode',
        ),
    ]
