# Generated by Django 3.1.1 on 2021-02-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='timestamp',
        ),
    ]
