# Generated by Django 3.1.1 on 2020-10-18 23:08
# Generated by Django 3.1.1 on 2020-10-18 22:48

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('products', 'product')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid1()
        row.save(update_fields=['slug'])
        
class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=500, unique=True),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

         migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=500, unique=True),
        ),
        
    ]